// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using myown.Context;

#nullable disable

namespace myown.Migrations
{
    [DbContext(typeof(SerpentContext))]
    [Migration("20230220123835_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("myown.Models.Serpent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CientificName")
                        .HasColumnType("TEXT");

                    b.Property<int>("FamilyType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PopularName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Serpent");
                });
#pragma warning restore 612, 618
        }
    }
}
